[general]
shuffle_caption = false
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = 1024
batch_size = 2
keep_tokens = 1

  [[datasets.subsets]]
  image_dir = '/workspace/input'
  class_tokens = 'GNAVTRTKN'
  num_repeats = 10